//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHIVAMFaceEcomm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductValues_view
    {
        public string AttributeValue { get; set; }
        public int Quantity { get; set; }
        public int ProductQuantityID { get; set; }
        public decimal Cost { get; set; }
        public string AttributeName { get; set; }
        public int Id { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public int productId { get; set; }
        public string ProductName { get; set; }
        public string SupplierName { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
    }
}
