//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuthentication.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emailrecord
    {
        public int Id { get; set; }
        public string Email_Sender { get; set; }
        public string Email_Receiver { get; set; }
        public string Send_Date { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
    }
}
