//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuthentication.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetAllEmail
    {
        public int id { get; set; }
        public string userId { get; set; }
        public string SenderId { get; set; }
        public string Subject { get; set; }
        public string ContentMsg { get; set; }
        public bool IsAttachment { get; set; }
        public string Attachment { get; set; }
        public bool IsRead { get; set; }
        public string SendingDate { get; set; }
        public string ReceiverId { get; set; }
    }
}
