//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuthentication.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public Plan()
        {
            this.PlanFeatures = new HashSet<PlanFeature>();
            this.Suppliers = new HashSet<Supplier>();
        }
    
        public int Id { get; set; }
        public string PlanName { get; set; }
        public string Plancode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int Sort { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public string PlanFrequency { get; set; }
        public decimal MonthlyPrice { get; set; }
        public decimal YearlyPrice { get; set; }
        public decimal TotalYearlyPrice { get; set; }
        public decimal TotalMonthlyPrice { get; set; }
        public int ProductBucketCount { get; set; }
        public bool IsActive { get; set; }
        public int UserBucketCount { get; set; }
    
        public virtual ICollection<PlanFeature> PlanFeatures { get; set; }
        public virtual ICollection<Supplier> Suppliers { get; set; }
    }
}
