//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuthentication.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductValues_view
    {
        public string AttributeValue { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> ProductQuantityID { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string AttributeName { get; set; }
        public Nullable<int> Id { get; set; }
        public int SupplierID { get; set; }
        public Nullable<int> productId { get; set; }
        public string ProductName { get; set; }
        public string SupplierName { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> CateogryID { get; set; }
        public string Description { get; set; }
    }
}
