//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuthentication.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAttributesRelation
    {
        public int Id { get; set; }
        public int SupplierID { get; set; }
        public int ProductAttributesId { get; set; }
        public Nullable<int> Product_Id { get; set; }
    
        public virtual ProductAttribute ProductAttribute { get; set; }
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
