//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuthentication.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.CustomerReviews = new HashSet<CustomerReview>();
            this.ProductAttributesRelations = new HashSet<ProductAttributesRelation>();
            this.ProductAttributeWithQuantities = new HashSet<ProductAttributeWithQuantity>();
            this.ProductImages = new HashSet<ProductImage>();
            this.WishLists = new HashSet<WishList>();
            this.Carts = new HashSet<Cart>();
        }
    
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public string Ranking { get; set; }
        public string SKU { get; set; }
        public string IDSKU { get; set; }
        public int SupplierID { get; set; }
        public int ManuFacturerID { get; set; }
        public int CateogryID { get; set; }
        public int UnitOfMeasuresId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int Sort { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<CustomerReview> CustomerReviews { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual ICollection<ProductAttributesRelation> ProductAttributesRelations { get; set; }
        public virtual ICollection<ProductAttributeWithQuantity> ProductAttributeWithQuantities { get; set; }
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual ICollection<WishList> WishLists { get; set; }
        public virtual ICollection<Cart> Carts { get; set; }
    }
}
