//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuthentication.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAttribute_view
    {
        public string AttributeName { get; set; }
        public string AttributeValue { get; set; }
        public int productId { get; set; }
        public int Quantity { get; set; }
        public decimal Cost { get; set; }
        public int Id { get; set; }
        public bool IsFeatured { get; set; }
    }
}
